config/routes.rb
GS::Application.routes.draw do
  resources :dashboard
  resources :home
  devise_for :users
  
  root "home#index"

  

end

app/models/song.rb
require 'active_model'
require 'carrierwave/orm/activerecord'

class Song < ActiveRecord::Base
	include ActiveModel::Model
	attr_accessible :title,:artist,:album,:musicfile
	belongs_to :user
	mount_uploader :musicfile, MusicfileUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :songs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
	@songs = Song.all
  end
  def show
  end
  def new
	@song = Song.new

  end
  def create
	@song = Song.new(params[:song])
	@song.save
	uploader = MusicfileUploader.new
	uploader.store!(:file)
	#puts uploader
	#puts @song
	#redirect_to dashboard_index_path
  end
  def edit
  end
  def update
  end
  def destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def show
  end
  def new
	
  end
  def create
  end
  def edit
  end
  def update
  end
  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dashboard/_form.html.erb
<%= form_for @song , url: {action: "create"} do |song|  %>
	<%= song.hidden_field :user_id %>
	<p>
		<%= song.label :title %>
		<%= song.text_field :title %>
	</p>
	<p>
		<%= song.label :artist %>
		<%= song.text_field :artist %>
	</p>
	<p>
		<%= song.label :album %>
		<%= song.text_field :album %>
	</p>
	<p>
		<%= song.file_field :musicfile %>
	</p>
	<p> 
		<%= song.submit  "Upload" %>		
	</p>
<% end %>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>


<audio id="player" src="D.mp3" type="audio/mpeg" controls="controls">
	Not supported
</audio>

<hr>

<%= link_to "New" ,  new_dashboard_path %>

app/views/dashboard/new.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

<%= render partial: "form" %>


<hr>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GS</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div>
        <ul>
                <li> <%=link_to "Home", root_path %> </li>
                <li> <%= link_to "Dashboard", dashboard_index_path %></li>
                <li> <%= link_to "Sign in", new_user_registration_path  %></li>
                <li> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        </ul>
</div>
        
<%= yield %>

</body>
</html>